# Este arquivo informa ao Hugging Face como construir o app automaticamente
# com base em arquivos que estão no GitHub

title: "IA Detector"
emoji: "🧠"
author: joaogerd
app_file: src/app.py
sdk: gradio
description: "Classificador de textos que identifica se o conteúdo foi escrito por um humano ou por uma IA usando BERTimbau."
repository: https://github.com/joaogerd/ia-detector
dependencies:
  - requirements.txt
  - environment.yaml

# Pode ser usado com deploy automático a partir do GitHub
